openapi: 3.0.0
info:
  title: Nonton.in API
  version: 1.0.0
  description: This API provides movie recommendations based on user preferences.

servers:
  - url: https://Nonton.in/deleteuser
    description: Main (production) server


paths:
  /users/{userId}:
    delete:
      summary: Delete a user
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: "user123"
      responses:
        '204':
          description: User deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []
