openapi: 3.0.0
info:
  title: Nonton.in API
  version: 1.0.0
  description: This API provides movie recommendations based on user preferences.

servers:
  - url: https://Nonton.in/user
    description: Main (production) server

paths:
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        description: The user to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - bearerAuth: []

